no-permissions: "&cYou don't have permissions to execute this command"

scoreboard-title: "&4&lDesire&e&lMC"
scoreboard-lines:
  - ""
  - "&4&l%player%"
  - "&7Rank&f: %rank%"
  - "&7Balance&f: %balance%"
  - "&7Gems&f: %gems%"
  - "&7&odesiremc.net"

spawn:
  x: 0
  y: 100
  z: 0
  pitch: 0
  yaw: 0

chat-format: "%rank% &r &7%player%&f: %message%"

balance:
  usage:
    - "balance add player amount"
    - "balance remove player amount"
    - "balance set player amount"
    - "balance check"
    - "balance checkplayer player"
  check: "You have %balance% of money"
  checkplayer: "%player% has %balance% of money"
  add: "You have added %balance% to %player%"
  set: "You have set %balance% to %player%"
  remove: "You have removed %balance% from %player%"
  lower0: "%player% does not have %balance% to remove"

gems:
  usage:
    - "gems add player amount"
    - "gems remove player amount"
    - "gems set player amount"
    - "gems check"
    - "gems checkplayer player"
  check: "You have %balance% of gems"
  checkplayer: "%player% has %balance% of gems"
  add: "You have added %balance% to %player%"
  set: "You have set %balance% to %player%"
  remove: "You have removed %balance% from %player%"
  lower0: "%player% does not have %balance% to remove"