name: SkyBlock
version: '${project.version}'
main: net.desiremc.SkyBlock
api-version: 1.18
commands:
  setspawn:
  spawn:
  balance:
  gems:
  vanish:
    aliases: [v]
  reclaim:
  staff:
    aliases: [staffmode, h]
  robot:
  kit:
  casino:
  fly:
  crate:
  automessager: